kodeklubben/oppgaver

nb-NO/scratch/egne/halloweenimasjon/halloweenimasjon.md, nb-NO/scratch/egne/hvor_i_all_verden/hvor_i_all_verden_1.md, nb-NO/scratch/egne/hvor_i_all_verden/hvor_i_all_verden_2.md, nb-NO/scratch/egne/norgestur/README.md, nb-NO/scratch/egne/norgestur/norgestur.md
I noen oppgaver lenker vi til eksterne filer (f.eks. bakgrunnsbilder). Tidligere ble det lenket til kodeklubben.github.io, men dette krevde litt logistikk rundt filer som må lastes opp og navn som endrer seg. Har endret lenkene slik at de peker til raw.githubusercontent.com/kodeklubben/ i stedet. Lenkene er litt "styggere", men samtidig tryggere i det de ikke skal endre seg i fremtiden.
=> Oppdaterte lenker til ressurser til å peke til raw.githubusercontent

README.md
`[tekst](bilde.png)` gir caption - som ofte ikke ønskes.
=> bildetekst skal være i " dersom caption ikke ønskes

nb-NO/python/tre_pa_rad_mot_datamaskinen/tre_pa_rad_mot_datamaskinen.md
Fikset dårlig rendring av kodeblokk (la til avsluttende <code>```</code>), i tillegg til at det ser ut som at rester av en yaml-header hadde forvillet seg ned til bunnen.
=> Fixed last codeblock++

src/scratch/3d_flakser/3d_flakser_2.md, src/scratch/flaksefugl/flaksefugl.md, src/scratch/frantic_felix/frantic_felix.md, src/scratch/hvor_i_all_verden/hvor_i_all_verden_2.md, src/scratch/hvor_i_all_verden/hvor_i_all_verden_3.md, src/scratch/labyrint/labyrint.md, src/scratch/lydmaskin/lydmaskin-opptaker.md, src/scratch/norgestur/norgestur.md, src/scratch/soloball/soloball.md, src/scratch/spokelsesjakten/spokelsesjakten.md, src/scratch/straffespark/straffespark.md
Det finnes stopp-klosser i to kategorier: Kontroll og tilleggsfunksjoner. Legger derfor til fargedirektiver (eg. kategoridirektiver) slik at disse rendres korrekt.
Egnedefinerte klosser trenger også fargedirektiver når de ikke vises i samme kodeblokk som der de ble definert.
=> Fargedirektiver på stoppklosser og egendefinerte klosser

src/python/skilpadder/skilpadder.md, src/python/skilpaddeskolen/skilpaddeskolen.md
det har sneket seg inn \r i *skilpadder* og *skilpaddeskolen* som gjør at
`yaml.loadFront` i `codeclub_lesson_builder/playlist.js` ikke fungerer
=> fiks carriage return på enden av linjer

.travis.yml, travis-install.sh
Noen ganger henger travis grunnet at `done()` aldri kalles (når siste lenke feiler). Dette er fikset i siste versjon av [node-spider](github.com/flesler/node-spider).
PR inkluderer også litt endringer i travis konfigurasjon:
- bruk cache på `node_modules`
- kjør testen med siste versjon av node
=> Stabil travis

src/processing/ekstern_processing_org/hello_processing.md
Som foreslått og raskt diskutert på Facebook.
Vi har på andre rene videokurs skrevet Video i tittelen. Burde vi ha det her også? Selv om det ikke er et rent videokurs?
Jeg tok også med en kort kommentar om at det er på engelsk. Er dette en grei måte å gjøre dette på?
=> Lenke til Processing.org sin kodetime-oppgave

src/scratch/straffespark/README.md, src/scratch/straffespark/straffespark.md
I oppgaven er det stort sett bare endret til inline-klosser der det passer.
I veiledningen er et par setninger forhåpentligvis gjort tydeligere.
=> Små oppdateringer i tekstene for Straffespark, oppgave og veiledning

setup.bat
Node bruker .cmd-filer som krever at man bruker call når man kjører dem fra batch-skript.
I skript bør man også bruke pushd og popd for å bevege seg mellom mapper.
=> Fikser at node dreper skriptet, og bytter til push pop istedenfor cd.

src/scratch/kart/kart.js
Nå skal denne fungere også i Firefox. Har ikke IE eller Safari så har ikke fått testet dem skikkelig.
Tidligere har det ikke skjedd noe når man har trykket `Last ned`-knappen i Firefox og IE (funker fint i Chrome, har ikke fått testet safari).
=> Fix for Firefox

src/web/partikkel_2/partikkel_2.md, src/web/partikkel_animasjon/partikkel_animasjon.md, src/web/partikkel_gravitasjon/partikkel_gravitasjon.md
`setInterval` kan i noen tilfeller kjøre `draw` _før_ `onload` har kjørt. Dette feiler, og akkurat nå feiler dette PDF-bygging (fiks på vei). Rydder likevel opp i denne bugen og endrer litt i teksten til oppgaven.
=> web partikkel: fiks racing feil med setInterval/onload

src/web/introduksjon_til_web/introduksjon_til_web.md
Jeg har alltid brukt _avsnitt_ når jeg snakker om `p`-tagger, ettersom paragrafer [for de aller, aller fleste har en smak av juss](https://www.google.no/search?q=paragraf) på norsk. Føyet til en liten relativ bisetning om sammenhengen.
=> Koble paragraf til et kjent synonym (avsnitt)

gulp
This makes it easier to build things into a different directory,
which you have to if you want to push the built HTML to your own
host.
=> Allow running the gulp script from a different directory

.travis.yml, deploy.sh
Raskere deploy ved å ikke bygge filer som ikke har endret seg.
Indekser vil alltid bygges, men ikke oppgaver som ikke har blitt endret og deres PDF.
Commit blir også ryddigere på https://github.com/kodeklubben/kodeklubben.github.io
=> Fast deploy

src/elm/10_fraktaler/10_fraktaler.md
Oppgaven mangler ```` etter en kodeblokk, som brekker mye av layouten. Fiks!
=> Fix missing trailing `` after code block

src/scratch/data_navn/data_navn.md, src/scratch/index.md
Lenken til dataverktøyet var tilgjengelig tidligere, men var visst bare sjekket rett inn på kodeklubben.github.io-repoet og ble borte når byggeren virket igjen.
Navnelisteoppgaven har vært tilgjengelig siden i høst, men ikke lenket opp.
+ http://oppgaver.kidsakoder.no/scratch/data/data.html
+ http://oppgaver.kidsakoder.no/scratch/data_navn/data_navn.html
Se #294 og #295 for opprinnelig PR
=> Legg til navnelisteoppgaven samt lenke til dataverktøyet

src/elm/08_mus/08_mus.md
Fjernet referanser til hendelsene DragAt og DragEnd, som ikke finnes.
=> Fiks feil i museoppgave

src/filtertags.md
Endret fra electronic til electronics. Ingen oppgaver er tagget med dette enda, så da slapp jeg å endre noe der.
Gjerne se over indenting også. Jeg måtte endre dette tidligere for at det ikke skulle feile i codeclub-veiwer. Men jeg er ikke så god i YAML...
=> electronics i filtertags

src/python/bokstaver/README.md, src/scratch/hoppehelt/README.md
To av lærerveiledningene kom ikke med i cc-viewer fordi de hadde tom linje i starten av dokumentet, så YAML ble ikke lest.
=> Fjernet tom linje i starten av dokumentet

src/elm/05_tegne/05_tegne.md
The old web page with an animated Bezier Curve editor got SSL errors, causing
the link checker to fail. Use a different application to avoid this.
This time, with just the one file that should be there.
=> Change bezier animation target

src/computercraft/sprettball/sprettball.md
a search-and-replace operation had previously replaced code in a code snippet, which it shouldn't have touched
Solves #612
=> fix syntax error in code snippet

filtertags/keys.md, filtertags/translation_da.md, filtertags/translation_en.md, filtertags/translation_nb.md, filtertags/translation_nn.md, filtertags/translation_sv.md, src/sonic_pi/index.md
Added `sound` as a topic in filtertags, to cover projects involving sound and music. Used sound instead of music to avoid clashes with `subject: music`.
Added `topic: sound`  to Sonic-Pi course, and fixed `music` wrongly tagged as `topic`.
=> New topic in filtertags; sound

filtertags/keys.md, filtertags/translation_da.md, filtertags/translation_en.md, filtertags/translation_nb.md, filtertags/translation_nn.md, filtertags/translation_sv.md
Trengs for PR https://github.com/kodeklubben/codeclub-viewer/pull/424
Legger til språk i filtertags, slik at det blir enklere i codeclub_viewer å behandle alle filter under ett. Riktignok er det slik at alle oversettelser av språk er lik (siden vi alltid skriver språkene på morsmålet sitt), men det gir mulighet for å endre, og som sagt, enklere å forholde seg til når alt er uniformt.
Retter også opp en liten feil.
=> Filtertags legg til spraak

filtertags/keys.yml, filtertags/translation_da.yml, filtertags/translation_en.yml, filtertags/translation_nb.yml, filtertags/translation_nn.yml, filtertags/translation_sv.yml
Ettersom md-filene i filtertags-mappen egentlig er yaml-filer, så har jeg gjort dem om til det.
Når denne PR'en er merget, så må https://github.com/kodeklubben/codeclub-viewer/pull/487 i codeclub-viewer også merges.
=> Convert all filtertag md-files to yml-files.

linter/LKK_auto_linter.py, linter/LKK_auto_linter.sh, linter/LKK_auto_linter_global.sh
Poenget med filene er og automatisk linte filene i stil med stil guiden vi har. Den er godt kommentert for å forklare akkuratt hva som lintes. I utgangspunktet er linteren satt opp slik at den aldri vil linte en fil to ganger. Da scriptet oppretter en temp fil, linter denne også renamer temp fila dersom denne er ulik den opprinnelige. Scriptet har dog to mindre problemer, som jeg er usikker på hvordan jeg kan fikse.
* Filene i lista under bygges hver gang auto_linteren kjøres over oppgavesammlingen. 
* Den bryter og sammen dersom filene inneholder mellomrom 
Litt usikker på hvordan jeg kan fikse problemet med mellomrom, men i utgangspunktet skal jo ikke filnavn eller mappenavn inneholde mellomrom. Angående første forstår jeg ikke hvorfor den sier at filene har endret seg når de ikke har …
=> Wrote basic linter

src/scratch/bursdag_i_antarktis/bursdag_i_antarktis.md, src/scratch/bursdag_i_antarktis/bursdag_i_antarktis_nn.md, src/scratch/felix_og_herbert/felix_og_herbert.md, src/scratch/flaksefugl/flaksefugl.md, src/scratch/flaksefugl/flaksefugl_nn.md, src/scratch/fyrverkeri/fyrverkeri.md, src/scratch/fyrverkeri/fyrverkeri_nn.md, src/scratch/jafsefisk/jafsefisk.md, src/scratch/jafsefisk/jafsefisk_nn.md, src/scratch/kingkong/kingkong.md, src/scratch/norgestur/norgestur.md, src/scratch/norgestur/norgestur_nn.md, src/scratch/orkenlop/orkenlop.md, src/scratch/orkenlop/orkenlop_nn.md, src/scratch/spokelsesjakten/spokelsesjakten.md, src/scratch/spokelsesjakten/spokelsesjakten_nn.md, src/scratch/tegneprogram/tegneprogram.md
For de oppgavene der det er relevant. *Merk* ikke endret for blokken `spill lyden <x> til den er ferdig` (som fortsatt heter slik i Scratch 3)
=> Scratch 2->3 spill lyden -> start lyden

src/scratch/jafsefisk/jafsefisk.md, src/scratch/jafsefisk/jafsefisk_nn.md
Et løsningsforslag til sak #1217, der det ble påpekt følgende tre problemer med formuleringen i Scratch-oppgaven "JafseFisk" som flere deltakere på en Kodeklubb ble forvirret over. Commitene i denne PR-en er rent kosmetiske, og kan testes ved å bygge og kjøre nettsiden lokalt.
1) **Linje 55 "Hvordan ser den ut? Hvorfor gjør den dette?" Dette er et retorisk spørsmål. Bør ikke ha checkbox.** Fjernet den tredje sjekkboksen og la teksten inn på det andre punktet.
2) **Linje 59 Barna har problemer med "manisk", foreslår å bare ha "flipping".** Fjernet ordet ''manisk'' i bokmålsversjonen.
3) **Ganske mange av barna hadde mistet byttedyret lenge før linje 181. Foreslår å legge inn "vis" kloss allerede rundt linje 142.** La til vis-blokken lenger opp i oppgaveteksten.
=> Formuleringer i oppgaven JafseFisk

src/arduino/ultralydsensor/ultralydsensor.md
The arduino code 
auto tid = pulseIn(ekko);
Would not compile, it gives this error message: "too few arguments to function 'long unsigned int pulseIn(uint8_t, uint8_t, long unsigned int)'"
My fix adds the missing HIGH argument and now the code compiles.
I tested it with a sensor and an arduino UNO 21.09.2020 and it works.
=> ultralydsensor.md - Fix to Arduino code

.github/workflows/test-and-deploy.yml
Hi,
Updated two github actions to newer version to fixes warning when action is run
See any action runs for the warning:
https://github.com/kodeklubben/oppgaver/actions/runs/4870480294
=> Update github action versions
