nb-NO/python/skilpaddefraktaler/skilpaddefraktaler.md, nb-NO/python/skilpaddekunst/skilpaddekunst.md, nb-NO/scratch/snoballkrig/README.md
=> fiks formatering på kodeblokker

nb-NO/python/roterende_firkant/roterende_firkant.md, nb-NO/python/roterende_firkant/step1.py, nb-NO/python/roterende_firkant/step2.py
Jeg anser meg selv som langt ifra ferdig med denne oppgaven, men tenkte jeg skulle se om jeg kunne få litt feedback. Med andre ord, jeg ønsker ikke at denne skal merges med det første.
Tanken min har vært at det hadde vært kult å få til noen enkle oppgaver med litt 3D-grafikk, og sette dem sammen som en såkalt spilleliste. Hvis man holder tungen litt rett i munnen så er det ikke så grusomt mange linjer kode som skal til for å få på plass noe kult heller. Kombinasjonen av python, pygame og OpenGL er overraskende enkel og grei, det eneste som kan være noe knot er å installere pakkene som trengs. 
Jeg tenker å legge listen der at jeg antar at de som gjennomfører oppgavene har en forståelse for løkker, if-setninger og funksjoner fra før av. Hvis jeg skulle forklart disse konseptene så hadde …
=> Utkast til OpenGL-oppgave med 3D-grafikk.

src/python/skilpaddefraktaler/skilpaddefraktaler.md
=> fiks kodefeil

README.md
=> Oppdaterte lenker fra nb-NO til src i hoved-README

src/web/lesson1/lesson1.md, src/web/lesson2/lesson2.md, src/web/lesson3/lesson3.md, src/web/lesson4/lesson4.md, src/web/lesson5/lesson5.md, src/web/volunteer-resources/saving-your-work.md
nødvendig for arve0/codeclub_lesson_builder#47
=> ordne opp i feil formatering av kodeblokker

.gitignore, deploy.sh
For å bruke scriptet:
- klon https://github.com/kodeklubben/kodeklubben.github.io først
- kjør ./deploy.sh
- vil pushe til kodeklubben.github.io om du har skrivetilgang på det repoet
- dersom du ikke ønsker pushe, endre `git push` i deploy.sh med `echo OK`
=> script for automatisk bygg

src/web/lesson1/lesson1.md, src/web/lesson2/lesson2.md, src/web/lesson3/lesson3.md, src/web/lesson4/lesson4.md, src/web/lesson5/lesson5.md
relevant for arve0/codeclub_lesson_builder#47
=> små bokstaver for kodeblokker

.travis.yml, setup
med en litt slem `rm -fr node_modules`
=> prøv npm install en gang til om den feiler

deploy.sh, gulp, pull_and_deploy.sh
Gjorde noen små endringer i bash-scriptene slik at de enklere kan kalles fra andre dir. Sørger kort oppsummert for at CWD er det dir som scriptene ligger i.
=> Pitteliten endring for å gjøre automatisk deploy enklere.

deploy.sh
Ny mini-PR. Jeg er ikke ekstremt stødig i bash, så vil gjerne at noen ser over dette. Det er testet og fungerer tilsynelatende bra.
=> Bugfix for å hindre at deploy.sh kræsjer når det ikke finnes en README.md

.travis.yml, deploy.sh
hendig når man skal sjekke linker kjapt ved endring av oppgaver
=> kjør "dist" eksplisitt, slik at links kan kjøres ved behov manuelt

src/python/kalkulator/kalkulator.md
To nye oppgaver. I begge oppgavene er det opp til ungene selv å skrive koden på egenhånd. 
Jeg har definert begge som vanskelige oppgaver (level 3), men er noe usikker på om Kalkulator (evt. begge) må justeres opp et hakk.
=> Python - Nye oppgaver: Gjettelek og Kalkulator

src/python/fargespill/fargespill.md
Endret font og lagt til .pack()
=> Endret introduksjonslabel

src/python/kuprat/kuprat.md, src/python/mattespill/mattespill.md, src/python/skilpadder/skilpadder.md, src/python/skilpaddeskolen/skilpaddeskolen.md
=> replace or remove new window to reflect new python

src/python/index.md, src/python/skilpadder/skilpadder.md
noe mer som burde bli tatt med?
=> oppdatert info om python

src/python2/index.md
Var litt rask med å kopiere Tjerands endringer over til videregående python, uten å fikse tittelen samtidig.
=> fiks navn til videregående python

src/scratch/index.md
Endret blokk til kloss
Bruker bakoverfnutter
Inkluderer begrepene skript og scene
=> Små endringer i infoteksten for Scratch

src/python2/hangman/hangman.md
=> python hangman: fiks test-overskrifter

src/scratch/bursdag_i_antarktis/bursdag_i_antarktis.md
Rapportert av @larsfk. Ikke verifisert av meg.
=> scratch: antarktis, fiks manglende "send melding [Navn1]"

src/python2/playlists/Python101.txt
=> La til spilleliste for videregaaende python

src/kodetimen/code_org/codestudio_barnehage.md, src/kodetimen/code_org/codestudio_mellomtrinn.md, src/kodetimen/code_org/codestudio_smatrinn.md, src/kodetimen/codecombat/codecombat.md, src/kodetimen/index.md, src/kodetimen/playlists/1_Barnehage.txt, src/kodetimen/playlists/2_Småtrinnet_1-4.txt, src/kodetimen/playlists/3_Mellomtrinnet_5-7.txt, src/kodetimen/playlists/4_Ungdomsskolen.txt, src/kodetimen/playlists/5_Videregående_skole.txt, src/kodetimen/processing/kodeklubben.md, src/kodetimen/processing/vesteraas.md, src/kodetimen/robotvenner/robotvenner.md
Utviklet på LKK-dugnad 18. oktober 2015
=> Et første utkast til materiell for kodetimen

src/scratch/breakout/breakout.md, src/scratch/snake/snake.md, src/scratch/straffespark/straffespark.md
Credit where credit is due ...
=> Oppdatert forfattere av Scratchoppgaver

src/scratch/snake/snake.md
Etter forslag fra Viggo Navarsete
=> Forbedret steg 3 i snake

src/kodetimen/code_org/codestudio_barnehage.md, src/kodetimen/playlists/2_Småtrinnet_1-4.txt, src/kodetimen/playlists/3_Mellomtrinnet_5-7.txt, src/kodetimen/playlists/4_Ungdomsskolen.txt, src/kodetimen/processing/kodeklubben.md, src/kodetimen/processing/vesteraas.md, src/kodetimen/scratch/kodeklubben.md
Lagt til lærerveiledninger for Processing og Scratch
=> Oppdateringer til kodetimen-sidene

src/arduino/ekstern_kodegenet/juleverksted.md, src/arduino/ekstern_kodegenet/kreativ_elektronikk.md, src/arduino/ekstern_kodegenet/penbot.md, src/arduino/ekstern_kodegenet/pixel_hunt.md, src/arduino/index.md, src/arduino/playlists/Kodegenet.txt
Gjort om Arduino til en kursside i stedet for en direktelenke til Kodegenet. Lagt inn Kodegenets oppgaver som enkeltoppgaver og en spilleliste.
@joachimhs Virker nivåinndelingen riktig? Kreativ elektronikk som intro (grønn), penbot og juleverksted som nybegynner (blå) og pixel hunt som erfaren (rød).
=> Arduino kurs

src/kodetimen/index.html
Denne er allerede live som quick-fix på gh-pages repo. Denne PR er en permanent fiks.
=> omdiriger /kodetimen -> /aa-kodetimen

src/scratch/straffespark/straffespark.md
Oppdatert litt tekst på straffespark for å prøve å forklare litt bedre noen av de vanligste feilene som gjøres
=> Scratch Straffespark: Oppdatert tekst

src/appinventor/index.md
=> Fikset encoding for forsideteksten på App Inventor 

src/appinventor/introduksjon/introduksjon.md
=> Legg til kilde og lisens for appinventor/komme i gang

src/aa-kodetimen/code_org/codestudio_mellomtrinn.md
Issue #154: La til lenker til code.org-oppleggene Star Wars og Minecraft.
=> Issue #154: La til lenker til code.org: Star Wars og Minecraft.

README.md
=> Oppdater bygger

src/unity/rull-en-ball/rull-en-ball.md
Fant og rettet opp noen småfeil i koden som følger med rull-en-ball-oppgaven.
=> [unity] småfeil i PlayerController-koden

.travis.yml
=> Travis: Removed pandoc dependency

deploy.sh
Takket være @NorwegianKiwi har vi nå mulighet for å [oversette webgrensesnittet](https://github.com/arve0/codeclub_lesson_builder/tree/master/assets/locales). Denne PR oppdaterer pekeren til cclb mot branchen master.
=> bruk cclb/master

src/python/lopende_strekmann/lopende_strekmann.md, src/python/roterende_firkant/roterende_firkant.md, src/web/forsvunnet_katt/forsvunnet_katt.md, src/web/ressurser/meet-the-browsers.md, src/web/ressurser/saving-your-work.md, src/web/style_nettsider/style_nettsider.md
Kom over disse syntaksfeilene. Bug var introdusert i #157.
=> fiks syntaks på diverse overskrifter

src/scratch/straffespark/README.md
Dette er et forslag til struktur for lærerveiledninger:
+ Forberedelser, med estimat for tidsbruk på oppgave og krav til forkunnskaper
+ Typiske utfordringer, med forslag til løsninger
+ Variasjoner
+ Tema, et forslag til noe som kan presenteres / diskuteres i plenum i sammenheng med oppgaven
Det er mulig det er litt ambisiøst med like detaljerte veiledninger for alle oppgaver, men jeg tror ihvertfall utfordringer er nyttige å få med. Og det hadde vært moro å få på plass en brukbar liste med tema som kan diskuteres.
=> Lærerveiledning for Straffespark

.gitmodules, setup
git submodule update --remote will pull lastest commit in branch master
Denne burde feile, ref #184
=> use latest master in cclb

src/scratch/interaktive_oppgaver/animasjon_med_navnet_ditt.md, src/scratch/interaktive_oppgaver/ballspillet_pong.md, src/scratch/interaktive_oppgaver/basketballkurver.md, src/scratch/interaktive_oppgaver/bjornebunken.md, src/scratch/interaktive_oppgaver/dans_dans_dans.md, src/scratch/interaktive_oppgaver/kom_i_gang_med_scratch.md, src/scratch/interaktive_oppgaver/lag_et_fotballspill.md, src/scratch/interaktive_oppgaver/lag_et_kort_til_en_venn.md, src/scratch/interaktive_oppgaver/lag_et_valentinsdag-kort.md, src/scratch/interaktive_oppgaver/lag_et_virtuelt_kjaeledyr.md, src/scratch/interaktive_oppgaver/leke_gjemsel.md, src/scratch/interaktive_oppgaver/lop_om_kapp.md, src/scratch/interaktive_oppgaver/ting_jeg_liker.md, src/scratch/playlists/Interaktive_oppgaver.txt
En samling av pekere til de interaktive oppgavene som er tilgjengelig i Scratchmiljøet (Hjelp i menyen > Alle tips)
=> Ny oppgavesamling med interaktive scratchoppgaver

src/computercraft/robotinvasjon/robotinvasjon.md
=> Robotinvasjon kodefeil

src/scratch/felix_og_herbert/felix_i_herbert-hr.md
La til form og kategori på de kroatiske kodeklossene slik at de rendrer bedre uten å sette språk til 'hr' i scratchblocks. Dette er egentlig ikke så viktig, men siden oppgaven er tilgjengelig gjennom søk kan vi like gjerne gjøre det :)
=> Fargelegg kodeklosser i Felix i Herbert (hr)

src/web/internett/internett.md
=> web: internett, fiks xray goggles

src/index.md
mange som spør/reagerer på over og under 12 år, og den ble skrevet da vi kun hadde materiell i scratch og python. kan diskuteres om vi burde si enda mer, for det er vanskelig å vite hva som anbefales dersom en er ny.
=> Velkommentekst

src/python/kuprat/kuprat.md
Det viser diff på første linje fordi filen er konvertert fra UTF-8 med BOM til vanlig UTF-8.
=> python/kuprat - utdyp om hva input() gjør

src/appinventor/AndroidWheresMyCar/AndroidWheresMyCar.md, src/appinventor/DigitalDoodle/digitaldoodle.md, src/appinventor/GetTheGold/getthegold.md, src/appinventor/HelloPurr/hellopurr.md, src/appinventor/MagicBall/magicball.md, src/appinventor/MapIt/MapIt.md, src/appinventor/MiniGolf/minigolf.md, src/appinventor/NFCCupGame/NFCCupGame.md, src/appinventor/OhMySpikes/OhMySpikes.md, src/appinventor/PaintPot/PaintPot1.md, src/appinventor/PaintPot/PaintPot2.md, src/appinventor/QuizMe/QuizMe.md, src/appinventor/SpaceInvaders/SpaceInvaders.md, src/appinventor/StockQuotes/stockquotes.md, src/appinventor/VideoWall/videowall.md, src/appinventor/Videokurs/videokurs.md, src/appinventor/playlists/Oppgaver på norsk.txt
det finnes mange veiledninger til app inventor på engelsk som eg har
linket opp for at barna som har kommet langt skal ha noe mer å jobbe med
og bli inspirert av
=> linket oppgaver

src/codestudio/AngryBirds/angrybirds.md, src/codestudio/AppLab/applab.md, src/codestudio/AppLab/applab_intro.md, src/codestudio/AppLab/applab_js.md, src/codestudio/Artist/artist.md, src/codestudio/ArtistApp/artistapp.md, src/codestudio/FlappyBird/flappybird.md, src/codestudio/Frost/frost.md, src/codestudio/Infinity/infinity.md, src/codestudio/Kurs1/kurs1.md, src/codestudio/Kurs2/kurs2.md, src/codestudio/Kurs3/kurs3.md, src/codestudio/Kurs4/kurs4.md, src/codestudio/Minecraft/minecraft.md, src/codestudio/PlayLab/playlab.md, src/codestudio/StarWars/starwars.md, src/codestudio/StarWars/starwars_js.md, src/codestudio/index.md
koblet opp og kategorisert alle opplegg på code.org, istedenfor å bare
lenke til code.org/learn.
=> codestudiooppgaver

src/python/skilpadder/skilpadder.md
=> Fiks en skrivefeil

src/scratch/jafsefisk/jafsefisk.md, src/scratch/soloball/soloball.md
ref arve0/codeclub_lesson_builder#206
=> scratch: vend @ -> vend venstre

src/scratch/hvor_i_all_verden/hvor_i_all_verden_2.md
Denne klossen har endret navn.
=> hvor i all verden 2: fiks flytt bakover lag

src/scratch/3d_flakser/3d_flakser_2.md
Ser ut som denne logiske feilen har vært tilstede siden starten! 😕 
https://github.com/kodeklubben/oppgaver/blame/7884a3d317f05c99e17a1d9b64d32ed5979381a0/scratch/kurs_viderekommende/3D_flaksefugl/3D_flakser_2.md
=> 3d flakser: fiks logisk feil ringY -> y

src/scratch/3d_flakser/3d_flakser_1.md
I noen tilfeller kan y-verdien være slik at gulvet i del 2 starter
slik at man taper umiddelbart.
=> 3d flakser 1: nullstill x og y ved nytt spill

src/web/trykkomania/trykkomania.md
Lagt til semicolon i koden på jsbin slik at fasiten ikke får feilmeldinger med jsbins standardkonfigurasjon. Lenkene i oppgaven er oppdatert.
=> trykkomania: fiks feilmeldinger i jsbin

src/appinventor/MapIt/MapIt.md
Ble oppdaget her: [https://github.com/NorwegianKiwi/codeclub-viewer/issues/6](https://github.com/NorwegianKiwi/codeclub-viewer/issues/6)
=> Fix invalid YAML in MapIt

src/arduino/blinkende_lysdiode/blinkende_lysdiode.md
Reverts kodeklubben/oppgaver#263
Filen er omdøpet i commit fra @snake66
=> Revert "Særsrkivningsfeil, "kodelinje" i ett ord :)"

src/web/del_inn_nettsiden/del_inn_nettsiden.md, src/web/lenk_sammen_nettsider/lenk_sammen_nettsider.md
Lenker i "Del inn nettsiden" og "Lenk sammen nettsider" er fikset.
=> Web: fikset lenker

src/arduino/ekstern_arduino_guiden/arduino_guiden.md
Reverts kodeklubben/oppgaver#141
=> Revert "La til lenke til den eksterne Arduino-Guiden"

src/scratch/kodeklubben_trysil_videokurs/crazy_eyes.md, src/scratch/kodeklubben_trysil_videokurs/flappy_bird.md, src/scratch/kodeklubben_trysil_videokurs/fotballtennis.md, src/scratch/kodeklubben_trysil_videokurs/intro_del_1.md, src/scratch/kodeklubben_trysil_videokurs/intro_del_2.md, src/scratch/kodeklubben_trysil_videokurs/intro_del_3.md, src/scratch/kodeklubben_trysil_videokurs/kanon.md, src/scratch/kodeklubben_trysil_videokurs/lavaball.md, src/scratch/kodeklubben_trysil_videokurs/skytespill.md, src/scratch/playlists/Kodeklubben_Trysil_videokurs.txt
La til Kodeklubben Trysil sine videoinstruksjoner for å lage spill i
Scratch
=> Ny Scratch-spilleliste

src/index.md
ref https://github.com/kodeklubben/kodeklubben.github.io/pull/8
Takk, @rocoty
=> index: fiks skrivefeil

src/web/trykkomania/trykkomania.md
Lest igjennom, gjort noen rettinger. Klar for PR.
=> Web: JS: Trykkmania

src/web/hei_js/hei_js.md, src/web/trykkomania/trykkomania.md
Små endringer i allerede eksisterende oppgave
- Skrevet om setninger
- Lagt til ekstra forklaringer
- Referanse til HTML: Publiser nettsiden din
=> Web: JS: Hei JavaScript

src/web/grunnleggende_js/grunnleggende_js.md
Ny oppgave med variabler, funksjoner, if/else og løkker. 
Trenger gjennomlesing!
=> Web: JS: Grunnleggende JavaScript

src/python/hvor_gammel_er_du/hvor_gammel_er_du.md
=> Python: Hvor gammel er du? Typo

src/web/partikkel_gravitasjon/partikkel_gravitasjon.md
Oppgaven er en videreføring av partikkel-animasjon og lærere deg hvordan du kan få et objekt til å falle og "sveve" ved hjelp av gravitasjon og ved å trykk på knapper.
=> Web: JS: Partikkel-gravitasjon

src/web/partikkel_2/partikkel_2.md
Videreutvikling av Partikkel-animasjon
Les commits for mer detaljer
=> Web: JS Partikkel-fest

src/web/partikkel_animasjon/partikkel_animasjon.md
Editoren min fjerner mellomrom på slutten av linjer.
=> web partikkel animasjon: fiks lenke

src/web/partikkel_gravitasjon/partikkel_gravitasjon.md
Fikser lenken `http://www.w3schools.com/jsref/event_onkeydown` --> `http://www.w3schools.com/jsref/event_onkeydown.asp`.
=> web partikkelgravitasjon: fiks lenke

src/python/hvor_gammel_er_du/alder.py, src/python/hvor_gammel_er_du/hvor_gammel_er_du.md
Har sjekket PDF lokalt, det fungerer.
Fixes #310.
=> python hvor gammel er du: oppdater år

src/computercraft/robotinvasjon/robotinvasjon.md
La til manglende paranteser for detectDown-kall i siste oppgave.
=> Fiks for siste kodeeksempel

src/web/en_hjemmeside/en_hjemmeside.md
=> Skriveleiffiks: omg_meg => om_meg

src/elm/playlists/Elm_fra_hei_til_spill.txt
=> Put tasks 1-7 in a playlist

src/elm/9_egen_kode/9_egen_kode.md, src/elm/playlists/Elm_fra_hei_til_spill.txt
Legger til oppgave skrevet av Erik til bruk på kurs 14/3.
=> Elm PR 12: Egen kode

src/web/hvor_er_html/hvor_er_html.md
Link to oppgaver.kidsakoder.no instead of kodeklubben.github.io.
=> Link to oppgaver.kidsakoder.no

src/web/hvor_er_html/hvor_er_html.md
Glømte originalt forfatter, legg til nå.
I tillegg: linjeskift på 80 tegn.
=> Set author on "Hvor er HTML"

src/index.md
Creates a TeacherInfo object from which [PR 222](https://github.com/kodeklubben/codeclub-viewer/pull/222) codeclub-viewer fetches and displays TeacherInfo.
=> Add teacherInfo

src/appinventor/index.md, src/arduino/index.md, src/codestudio/index.md, src/computercraft/index.md, src/elm/index.md, src/javafx/index.md, src/kodu/index.md, src/kommandolinje/index.md, src/learntomod/index.md, src/legomindstorms/index.md, src/processing/index.md, src/python/index.md, src/rpi/index.md, src/scratch/index.md, src/swift/index.md, src/unity/index.md, src/uten_datamaskin/index.md, src/web/index.md
#358 Removes all operativsystem-tags to remove operativsystem from filter
=> Remove operativsystem-tags

src/index.md
Endret teacherInfo til info og la til student. Vet ikke hva som skal stå inne i teacherinfoBox eller welcomeBox, men nå ligger alt klart i hvert fall
=> Welcome box

src/index.md
This makes the text in the welcoming info boxes (more) meaningful.
=> Add proper info text for teacher, assistant and student

src/javafx/fxmllogo/fxmllogo.md, src/javafx/helloworld/helloworld.md, src/python/kuprat/kuprat.md, src/python/lopende_strekmann/lopende_strekmann.md, src/python/mattespill/mattespill.md, src/python/skilpaddefraktaler/skilpaddefraktaler.md, src/python/skilpaddekunst/skilpaddekunst.md, src/web/animasjon/animasjon.md, src/web/del_inn_nettsiden/del_inn_nettsiden.md, src/web/en_hjemmeside/en_hjemmeside.md, src/web/grunnleggende_js/grunnleggende_js.md, src/web/introduksjon_til_web/introduksjon_til_web.md, src/web/layout/layout.md, src/web/lenk_sammen_nettsider/lenk_sammen_nettsider.md, src/web/lyd_og_bilde/lyd_og_bilde.md, src/web/partikkel_2/partikkel_2.md, src/web/partikkel_animasjon/partikkel_animasjon.md, src/web/partikkel_gravitasjon/partikkel_gravitasjon.md, src/web/publiser/publiser.md, src/web/skjul_ninjaene/skjul_ninjaene.md
Noen gamle oppgaver manglet forfatter (evt oversetter for de som ble oversatt fra Codeclub UK).
Har lagt til disse etter beste evne :smile: Det var også et par oppgaver som brukte `Author` hvor det skal være `author` i yaml-taggen ...
=> Lagt til manglende forfatter eller oversetter

src/elm/11_prosjekt/11_prosjekt.md
Åpen siste oppgave. Litt starthjelp til spillprogrammering.
Jeg får ikke fargelagt syntaks når jeg kjører denne lokalt med `./gulp`. Har jeg gjort noe feil? @arve0 @gahjelle?
=> Elm: Åpen start på spilloppgave

src/level-config.json
Now gets level text from [captions_](https://github.com/kodeklubben/codeclub-viewer/tree/master/src/constants) in codeclub-viewer, level-config.json is no longer in use.
=> Remove level-config.json

src/scratch/astrokatt/README.md
=> Endringer i struktur, syntaks og nivå i Astrokatt, og ny branch for å unngå commit-feil. 

src/filtertags.md
Et utkast til filen for filtergrupper og tagger som er lovlige
=> First draft of filtertags

src/appinventor/index.md, src/arduino/index.md, src/codestudio/index.md, src/computercraft/index.md, src/elm/11_prosjekt/11_prosjekt.md, src/elm/index.md, src/filtertags.md, src/javafx/index.md, src/kodu/index.md, src/kommandolinje/index.md, src/learntomod/index.md, src/legomindstorms/index.md, src/processing/index.md, src/python/index.md, src/rpi/index.md, src/scratch/index.md, src/swift/index.md, src/unity/index.md, src/uten_datamaskin/index.md, src/web/index.md
Disse kan fjernes nå som alle oppgavene skal bli tagget
=> Fjernet tags for indexfiler til kurs.

src/web/playlists/HTML.txt
feil i path, fikses her. konsekvens hos meg: gulp vil ikke kjøre om ikke
dette er korrekt.
=> fix web playlist

src/web/grunnleggende_js/README.md
=> Utkast til ferdigstilt lærerveiledning for Web: JS: Grunnleggende JavaScript

src/kommandolinje/learnshell/learnshell.md, src/python/tre_pa_rad/README.md, src/python/tre_pa_rad_mot_datamaskinen/README.md, src/scratch/3d_flakser/README.md, src/scratch/asteroids/README.md, src/scratch/snoballkrig/README.md
=> Fikse "broken links"

src/python/stjerner_og_galakser/README.md
stjerner_og_galakser/README.md har en `-` for mye i frontmatter. skal
bare ha 3, ikke 4.
=> fikser frontmatter i veiledning

src/python/gjettelek/README.md
@tjesi Husk å teste lokalt når du gjør review.
=> fjern newline på første linje

src/processing/ekstern_processing_org/hello_processing.md
=> Fjernet del av tittel

src/python/tre_pa_rad_mot_datamaskinen/tre_pa_rad_mot_datamaskinen.md
=> Skrivefeil i tags

README.md
Update description in README to match #548.
=> Readme: describe one folder per task

src/elm/03_moduler_elm_reactor/03_moduler_elm_reactor.md
- Remove Notepad recommendation.
- Spell Notepad++ correctly
=> Fix editor recommendations

src/kommandolinje/learnshell/learnshell.md, src/kommandolinje/norskintro/norskintro.md
Hei,
Jeg har sett på oppgavesettene vi linker til på kommandolinje-kurset.
- Codecademy er knallbra. God tilbakemelding, god informasjon om hva som skal skje, god progresjon, god hjelp underveis. Dette kan jeg anbefale.
- Kursene jeg fjernet er gode for personer på universitetsnivå, men blir fryktelig mye tekst underveis for barn og ungdommer. Det dekkes heller ikke viktige ting som man får med seg om man gjør Codecademy-kurset.
Jeg mener at vi bør fjerne disse to. @tjesi @NorwegianKiwi : dere har redigert filene tidligere. Er dere enige?
Teodor
=> Diskusjon: Fjern vanskelige oppgaver fra kommandolinje-kurset

src/kommandolinje/linuxjourney/linuxjourney.md
Linux Journey er oversiktelig introduksjon til alt som har med Linux å gjøre. Den går langt i dybden. Skulle ønske jeg hadde fått den anbefalingen for ti år siden!
=> Link to Linux Journey

src/kommandolinje/overthewire-bandit/bandit.md
Bandit er en kul serie oppgaver som gir praktiske utfordringer. Hver utfordring ender opp med å gi brukeren et passord. Passordet låser opp neste nivå!
=> Link til Over The Wire: Bandit

src/kommandolinje/mystery/mystery.md
Hei!
Har sett litt på kommandolinjeoppgavene. clmystery er en herlig oppgave. Men den er vanskelig! Den gir ikke steg-for-steg-instruksjoner som vi ofte ellers har på nybegynner-oppgaver. Mener derfor at denne bør "oppgraderes" til erfaren.
Teodor
=> Øk vanskeldighetsgraden for clmystery

src/appinventor/lag_din_egen_app/README.md, src/arduino/blinkende_lysdiode/README.md, src/kodu/videoer/lisa.md, src/kodu/videoer/oystein.md, src/kodu/videoer/stig.md, src/kommandolinje/codeacademy/codeacademy.md, src/kommandolinje/linuxjourney/linuxjourney.md, src/kommandolinje/mystery/mystery.md, src/kommandolinje/overthewire-bandit/bandit.md, src/legomindstorms/Trykksensor/3robot.md, src/uten_datamaskin/codeorg/codeorg.md
Var 11 oppgaver som mangler "language" i YAML :)
src/uten_datamaskin/codeorg/codeorg.md fungerer ikke, så kanskje jeg bare skulle slettet den, hvis ingen finner riktig link for meg
=> Legger til språk på resterende oppgaver

src/arduino/blinkende_lysdiode/blinkende_lysdiode.md, src/elm/04_input/04_input.md, src/python/fargespill/README.md, src/python/gjettelek/README.md, src/python/hangman/README.md, src/python/hangman/hangman.md, src/python/hangman2/README.md, src/python/hemmelige_koder/README.md, src/python/kalkulator/README.md, src/python/lister_og_indekser/README.md, src/python/lopende_strekmann/README.md, src/python/repetisjon/README.md, src/python/skilpaddeskolen/README.md, src/scratch/hvor_i_all_verden_del3/hvor_i_all_verden_3.md, src/web/ressurser/README_en.md
Løser issue #628 (og https://github.com/kodeklubben/codeclub-viewer/issues/354, ihvertfall midlertidig inntil hvis https://github.com/linsir/markdown-it-task-checkbox/issues/8 blir løst).
=> Fjerne all non-breaking spaces

src/scratch/astrokatt/astrokatt.md
Irritert meg over denne i her gang jeg får inn et nytt barn... Den heter legg foran i Scratch (men mulig den har hatt navnet legg øverst tidligere)
=> Retter navnet på blokken

src/web/en_hjemmeside/en_hjemmeside.md
ordnet en tag fra backslash til slash (shift 7).
=> Ordnet en tag ul

src/scratch/snurrige_figurer/snurrige_figurer.md
I oppgaven snurrige figurer er det brukt punkter istedet for checkboxes. Endret disse til checkboxes.
=> Changed bullet-points to checkboxes

src/processing/farger/farger.md
Dette er første gang jeg forsøker å bidra med noe her, så det kan være noe jeg har misforstått 😅 
Jeg har lagt til presisering på hvor variablene skal ligge i linje 383 og 487, i henhold til min forståelse av issue #598 🐶
=> #598 la til presisering l383 og l487

src/scratch/straffespark/straffespark.md
Opprinnelig forslag fungerer ikke altid hos meg, mens 'vent ' sekunder' gjør det
=> Endret måte som forhindrer at ballen beveger seg for tidlig

src/codecademy/data.yml, src/coder_dojo/data.yml, src/khan_academy/data.yml, src/kodegenet/data.yml, src/kodeknekkerne/data.yml, src/raspberry_pi/data.yml, src/sonic_pi/data.yml
Enten så er et kurs eksternt uansett språk, eller så er det det ikke. Da er det greit å gi beskjed om dette i den språk-uavhengige data.yml.
=> Legg til isExternal i data.yml for eksterne kurs

filtertags/translation_da.yml, filtertags/translation_en.yml, filtertags/translation_nb.yml, filtertags/translation_nn.yml, filtertags/translation_sv.yml
Denne endringer påvirker bare de nye sidene.
Jeg synes det ser litt rart ut at det f.eks. står "Se denne siden på Norsk nynorsk". Det virker mer logisk at det skal stå "Se denne siden på Nynorsk".
Forøvrig, bør da også "Norsk bokmål" endres til "Bokmål", eller er det greit?
=> Endre navnet på nynorsk fra "Norsk nynorsk" til "Nynorsk"

src/python/fargespill/fargespill.md
siden brekker pga ustabil nettside
=> fjerne url fra fargespill

src/python/hemmelige_koder/lesson.yml
=> Update lesson.yml in Hemmelige Koder

src/processing/bildepresentasjon/README.md, src/processing/bildepresentasjon/lesson.yml, src/processing/uendelig_bakke/README.md, src/processing/uendelig_bakke/lesson.yml
=> Add lesson files in processing

src/computercraft/installasjon/installasjon.md
removed an / in the end of url
=> fix 404 error in computercraft

src/scratch/flaksefugl/README.md
la til {.activity} for å få checkboxes til å funke som de skal
=> fikse flaksefugl readme

src/python/hangman2/hangman2.md, src/python/hangman2/hangman2_nn.md, src/python/lopende_strekmann/lopende_strekmann.md, src/python/lopende_strekmann/lopende_strekmann_nn.md, src/python/sprettball/sprettball.md, src/python/sprettball/sprettball_nn.md
Lagt til steg 0 i PGZ-oppgåvene om installering av PyGame Zero.
=> Python: Installasjon av PGZero

src/scratch/asteroids/README.md, src/scratch/breakout/README.md, src/scratch/donkey_kong/README.md, src/scratch/lunar_lander/README.md, src/scratch/pong/README.md, src/scratch/snake/README.md
Bruk melding i staden for grønt flagg for å starte spela.
=> Nytt tips til klassikar-oppgåvene

src/scratch/data_navn/README_nn.md
=> Add quotes

.travis.yml
Måtte fikse folder som deploy kjøres fra.
Se linje 2631 i loggen her: https://travis-ci.org/kodeklubben/oppgaver/builds/419292312
La også på at deploy bare skal kjøres ved merge til non-fork repo
=> Auto deploy2

.travis.yml
Deploy to kodeklubben/kodeklubben.github.io instead of norwegiankiwi/kodeklubben.github.io
=> Deploy to kodeklubben/kodeklubben.github.io 

src/scratch/felix_og_herbert/felix_og_herbert.md
Mange barn kan ikke lage egen scratchkonto. Jeg har lagt til tekst som passer dette.
=> La til tekst om innlogging for Scratch 3

src/python/index.md
=> Legg til at oppgavene forutsetter Python 3

src/scratch/astrokatt/astrokatt.md, src/scratch/astrokatt/astrokatt_nn.md
=> Betre instruksjon for oppstart

src/python/diffie-hellman/diffie-hellman.md
Fiksa lenke (#955) og justert oppsett i henhald til avtalte konvensjonar.
=> Fiks lenke til Primtall

src/python/hvor_gammel_er_du/hvor_gammel_er_du.md, src/python/hvor_gammel_er_du/hvor_gammel_er_du_nn.md
=> Fjernar årstal frå oppgåva

src/scratch/fyrverkeri/fyrverkeri.md, src/scratch/kingkong/kingkong.md, src/scratch/kingkong/kingkong_nn.md, src/scratch/tegneprogram/tegneprogram.md
legg foran --> legg foran alt
punktgrafikk --> pikselgrafikk
museknappen er nede --> museknappen er trykket
For de oppgaver der det var relevant
=> Tre endringer Scratch2 -> 3

src/scratch/fyrverkeri/fyrverkeri.md, src/scratch/kingkong/kingkong.md, src/scratch/kingkong/kingkong_nn.md, src/scratch/tegneprogram/tegneprogram.md
Reverts kodeklubben/oppgaver#983
=> Revert "Tre endringer Scratch2 -> 3"

src/microbit/pxt_blinkende_hjerte/lesson.yml, src/microbit/pxt_blinkende_lys/lesson.yml, src/microbit/pxt_det_regner_mat/lesson.yml, src/microbit/pxt_himmelfall/lesson.yml, src/microbit/pxt_lysmusikk/lesson.yml, src/microbit/pxt_nodt_eller_sannhet/lesson.yml, src/microbit/pxt_rakettoppskytning/lesson.yml, src/microbit/pxt_send_en_hemmelig_beskjed/lesson.yml, src/microbit/pxt_spaa_fremtiden_med_bilder/lesson.yml, src/microbit/pxt_spill_en_melodi/lesson.yml, src/microbit/pxt_tell_med_knapper/lesson.yml, src/microbit/pxt_tell_med_lokker/lesson.yml, src/microbit/pxt_terning/lesson.yml, src/microbit/pxt_vis_navnet_ditt/lesson.yml, src/microbit/python_music/lesson.yml, src/microbit/python_radio/lesson.yml, src/microbit/python_speech/lesson.yml, src/microbit/python_storage/lesson.yml
oppdatert flere lesson.yml med "electronics"
=> oppdatert flere lesson.yml med "electronics"

src/python/lopende_strekmann/lopende_strekmann.md, src/python/lopende_strekmann/lopende_strekmann_nn.md, src/python/sprettball/sprettball.md, src/python/sprettball/sprettball_nn.md, src/python/sprettball/sprettball_solution.py
=> Oppdatere PGZ-oppgaver

src/python/gjettelek/gjettelek.md, src/python/gjettelek/gjettelek_nn.md, src/python/hangman2/hangman2.md, src/python/hangman2/hangman2_nn.md, src/python/hash-funksjoner/hash-funksjoner.md, src/python/hvor_gammel_er_du/hvor_gammel_er_du.md, src/python/kalkulator/kalkulator.md, src/python/kalkulator/kalkulator_nn.md, src/python/kryptonott/kryptonott.md, src/python/kryptonott/kryptonott_nn.md, src/python/lister_og_indekser/lister_og_indekser.md, src/python/lister_og_indekser/lister_og_indekser_nn.md, src/python/mattespill/mattespill.md, src/python/mattespill/mattespill_nn.md, src/python/ordboeker/ordboeker.md, src/python/ordboeker/ordboeker_nn.md, src/python/passordlagring/passordlagring.md, src/python/skilpaddetekst/skilpaddetekst.md, src/python/skilpaddetekst/skilpaddetekst_nn.md, src/python/tekst_abc/tekst_abc.md, src/python/tekst_abc/tekst_abc_nn.md, src/python/tre_pa_rad/tre_pa_rad.md, src/python/tre_pa_rad/tre_pa_rad_nn.md
Ikke ferdig for merging!
Addresserer #635. Her er endringer gjort i de første tre (av mange) oppgaver som inneholder 'streng'. Setter pris på tilbakemelding om dette går i riktig retning. @tskauli
=> 'streng' -> 'tekst' i Python oppgaver

src/microbit/pxt_blinkende_hjerte/README.md, src/microbit/pxt_blinkende_lys/README.md, src/microbit/pxt_det_regner_mat/README.md, src/microbit/pxt_gangespill/README.md, src/microbit/pxt_hermegaasa/README.md, src/microbit/pxt_himmelfall/README.md, src/microbit/pxt_nodt_eller_sannhet/README.md, src/microbit/pxt_rakettoppskytning/README.md, src/microbit/pxt_send_en_hemmelig_beskjed/README.md, src/microbit/pxt_snake/README.md, src/microbit/pxt_spaa_fremtiden_med_bilder/README.md, src/microbit/pxt_stein_saks_papir/README.md, src/microbit/pxt_tell_med_knapper/README.md, src/microbit/pxt_tell_med_lokker/README.md, src/microbit/pxt_terning/README.md, src/microbit/pxt_vis_navnet_ditt/README.md, src/microbit/python_buttons/README.md, src/microbit/python_direction/README.md, src/microbit/python_gestures/README.md, src/microbit/python_hello_world/README.md, src/microbit/python_movement/README.md, src/microbit/python_musikk/README.md, src/microbit/python_network/README.md, src/microbit/python_random/README.md
Fiksa sjekkliste kompetansemål, oppdatert relevante fag
=> Micro:bit - kompetansemål og fag

src/microbit/pxt_kompass/lesson.yml
=> Fix missing letter

src/microbit/pxt_kompass/kompass_nn.md
Med kode som tekst, ikkje bilete.
=> Microbit Kompass nn

src/microbit/pxt_frustrasjon/frustrasjon.md, src/microbit/pxt_frustrasjon/frustrasjon_nn.md
Oppdatert bokmål og nynorsk versjon med microbit-blokker og code-tags
=> PXT_Frustrasjon:Oppdatert

src/microbit/pxt_kjoleskapsdoren/kjoleskapsdoren.md, src/microbit/pxt_kjoleskapsdoren/lesson.yml
Et program som spiller musikk og blinker når lyset i kjøleskapet har vært på for lenge.
=> PXT_Har_du_lukket_kjøleskapsdøren: Ny Oppgave

src/microbit/pxt_temperaturforandringer/lesson.yml, src/microbit/pxt_temperaturforandringer/temperaturforandringer.md
Oppgave som tar utgangspunkt i oppgaven "Temperatur". Her utvider vi oppgaven slik at vi kan ta flere målinger ved å trykke på knapp A. Disse blir så lagret i en liste slik at vi senere kan se hvordan enten temperaturen i ett enkelt rom har endret seg, eller hvordan temperaturen varierer ute og inne.
=> PXT_Temperaturforandringer: Ny oppgave

src/microbit/pxt_er_du_rask_nok/lesson.yml, src/microbit/pxt_er_du_rask_nok/rask_nok.md
Et spill hvor det er om å gjøre å reagere så raskt som mulig. Nå en pil vises på skjermen er det bare én knapp/knappekombinasjon du kan trykke for  å få poeng. Feil trykk gir minuspoeng.
=> PXT_Er_du_rask_nok: Ny oppgave

src/microbit/pxt_flappy_bird/flappy_bird.md, src/microbit/pxt_flappy_bird/lesson.yml
oppgave som lager en etterligning av det populære spillet flappy bird.
=> PXT_Flappy_bird: Ny oppgave

src/microbit/pxt_microbit_repeater/lesson.yml, src/microbit/pxt_microbit_repeater/repeater.md
En oppgave hvor vi lager kode som kan lastes ned på flere micro:biter for å sende fra én til neste og neste osv., slik at man kan sende lengre enn rekkevidden til én enkelt micro:bit tillater.
=> PXT_Microbit_repeater: Ny Oppgave

src/microbit/pxt_fjernstyr_en_venn/fjernstyr.md, src/microbit/pxt_fjernstyr_en_venn/lesson.yml
Morsom lek hvor man sender piler til en annen microbit for å styre personen i riktig retning.
=> PXT_Fjernstyr_en_venn: Ny oppgave

src/microbit/pxt_klokka_tikker/klokka_tikker.md, src/microbit/pxt_klokka_tikker/lesson.yml
Et spill hvor spillerne skal komme på flest svar til en kategori mens microbiten teller ned fra ti sekunder.
=> PXT_Klokka_tikker:Ny Oppgave

src/scratch/flaksefugl/flaksefugl.md, src/scratch/flaksefugl/flaksefugl_nn.md
Det trengs noen endringer i teksten for å passe til scratch 3.
=> Justeringer for scratch 3

src/scratch/gangemesteren/gangemesteren.md, src/scratch/gangemesteren/gangemesteren_nn.md
Arbeid på branchen:
[x] #1221 Erstattet brikken "slett" med brikken "slett alt". Testes ved å bygge og kjøre nettsiden lokalt
=> Korriger kodebrikke i oppgaven "Gangemesteren"

src/python/hash-funksjoner/hash-funksjoner.md, src/python/regn_med_lokker/regn_med_lokker.md, src/python/regn_med_lokker/regn_med_lokker_nn.md, src/python/repetisjon/repetisjon.md, src/python/repetisjon/repetisjon_nn.md
Selvfølgelig bare et forslag fra min side, men kan kanskje være greit å velge et annet variabelnavn enn `sum` i eksemplene, slik at ingen får det inn som en vane, siden navnet da maskerer den innebyggde `sum()`-funksjonen.
=> Kanskje greit å ikke maske innebygget sum()-funksjon

src/scratch/halloweenimasjon/README.md, src/scratch/halloweenimasjon/README_nn.md
=> Oppdatert kompetansemål bokmål og nynorsk Halloweenanimasjon

src/microbit/pxt_lysmusikk/README.md, src/microbit/pxt_lysmusikk/README_nn.md, src/microbit/pxt_lysmusikk/lesson.yml
=> Oppdatert kompetansemål m:b-PXT-lysmusikk

src/microbit/python_movement/README.md, src/microbit/python_movement/README_nn.md, src/microbit/python_movement/lesson.yml, src/microbit/python_movement/python_movement_nb.md, src/microbit/python_movement/python_movement_nn.md
Oppdatert LV bm og nn + tags. La til editor forklaring.
Lagt til oppgavesamling forklaring + link til forrige og neste oppgave.
=> Oppdatert kompetansemål m:b-python-movement

src/microbit/python_network/README.md, src/microbit/python_network/README_nn.md, src/microbit/python_network/lesson.yml, src/microbit/python_network/python_network_nb.md, src/microbit/python_network/python_network_nn.md
Oppdatert LV bm og nn + tags. La til editor forklaring.
Lagt til oppgavesamling forklaring + link til forrige oppgave
=> Oppdatert kompetansemål m:b-python-nettverk

src/microbit/pxt_joystick/README.md, src/microbit/pxt_joystick/joystick.md, src/microbit/pxt_joystick/lesson.yml
Opprettet LV bm og oppdatert tags.
Oppgaven: Fikset grå genererte kodeblokker i steg 2, endret tekst-blokker til microbit-blokker + fikset "utfordring"-boks
=> Opprettet LV med kompetansemål m:b-PXT-joystick

src/microbit/pxt_kjoleskapsdoren/README.md, src/microbit/pxt_kjoleskapsdoren/kjoleskapsdoren.md, src/microbit/pxt_kjoleskapsdoren/lesson.yml
Oppgaven: Fikset kodefeil i de genererte kodeblokkene
=> Opprettet LV med kompetansemål m:b-PXT-kjoleskapsdoren

src/microbit/pxt_mentometer/README.md, src/microbit/pxt_mentometer/lesson.yml, src/microbit/pxt_mentometer/mentometer.md
Oppgaven: Endret tekst-blokker til microbit-blokker, fikset grå blokker i de genererte kode-blokkene, endret 255 til 0 i kodeeksempelet til knapp-B, fikset "utfordring"-boks.
=> Opprettet LV med kompetansemål m:b-PXT-mentometer

src/microbit/pxt_spaa_fremtiden_med_bilder/README.md, src/microbit/pxt_spaa_fremtiden_med_bilder/README_nn.md, src/microbit/pxt_spaa_fremtiden_med_bilder/lesson.yml
=> Oppdatert kompetansemål m:b-PXT-spaa-fremtiden-med-bilder

src/microbit/pxt_snake/README.md, src/microbit/pxt_snake/README_nn.md
=> Oppdatert kompetansemål m:b-PXT-snake

src/microbit/pxt_nodt_eller_sannhet/README.md, src/microbit/pxt_nodt_eller_sannhet/README_nn.md
Oppdatert LV bm og nn + la til ekstra læringsmål
=> Oppdatert kompetansemål m:b-PXT-nodt-eller-sannhet

src/microbit/pxt_hjerneteppe/README.md, src/microbit/pxt_hjerneteppe/lesson.yml
=> Opprettet LV med kompetansemål m:b-PXT-hjerneteppe

src/microbit/pxt_flappy_bird/README.md, src/microbit/pxt_flappy_bird/lesson.yml
=> Opprettet LV med kompetansemål m:b-PXT-flappy bird

src/microbit/pxt_fjernstyr_en_venn/README.md, src/microbit/pxt_fjernstyr_en_venn/fjernstyr.md, src/microbit/pxt_fjernstyr_en_venn/lesson.yml
Oppgave: Fikset innrykk på nøstede lister
=> Opprettet LV med kompetansemål m:b-PXT-fjernstyr-en-venn

src/microbit/pxt_temperaturforandringer/README.md, src/microbit/pxt_temperaturforandringer/lesson.yml, src/microbit/pxt_temperaturforandringer/temperaturforandringer.md
Oppgave: La til to microbit-blokker i Steg 1.
=> Opprettet LV med kompetansemål m:b-PXT-temperaturforandringer

src/web/publiser/README.md, src/web/publiser/lesson.yml, src/web/publiser/publiser.md, src/web/publiser/publiser_nn.md
Oppdatert LV bm + tags
Oppgaven: Fikset litt formatering + la til {target=_blank} på linker
=> Oppdatert kompetansemål web-publiser

src/web/partikkel_2/README.md, src/web/partikkel_gravitasjon/README.md, src/web/partikkel_gravitasjon/lesson.yml, src/web/partikkel_gravitasjon/partikkel_gravitasjon.md, src/web/partikkel_gravitasjon/partikkel_gravitasjon_nn.md
=> Oppdatert kompetansemål web-partikkel-2 + web-partikkel-gravitasjon

src/web/lyd_og_video/README.md, src/web/lyd_og_video/lesson.yml, src/web/lyd_og_video/lyd_og_video.md, src/web/lyd_og_video/lyd_og_video_nn.md
Oppdatert LV bm + tags, la {target=_blank} til på link.
Oppgave: Norsk forklaring + skrivefeil
=> Oppdatert kompetansemål web-lyd-og-bilde

src/web/lenk_sammen_nettsider/README.md, src/web/lenk_sammen_nettsider/lenk_sammen_nettsider.md, src/web/lenk_sammen_nettsider/lenk_sammen_nettsider_nn.md, src/web/lenk_sammen_nettsider/lesson.yml
Oppdatert LV bm + tags.
Skiftet alle ulv.no linker + lagt til {target=_blank} + skrivefeil
=> Oppdatert kompetansemål web-lenke-sammen-nettsider

src/web/trykkomania/README.md, src/web/trykkomania/lesson.yml, src/web/trykkomania/trykkomania.md, src/web/trykkomania/trykkomania_nn.md
Oppdatert LV bm + tags, lagt til forklaring om forskjell på kode i steg 7, lagt kodelinje for å få "Fremgangsmåte"-overskrift ut av boksen.
Oppgaven: Fikset kode for å flytte poeng-boksen
=> Oppdatert kompetansemål web-trykkomania

src/web/tekststil/README.md, src/web/tekststil/lesson.yml
=> Oppdatert kompetansemål web-tekststil

src/web/partikkel_animasjon/README.md, src/web/partikkel_animasjon/lesson.yml, src/web/partikkel_animasjon/partikkel_animasjon.md, src/web/partikkel_animasjon/partikkel_animasjon_nn.md
Oppdatert LV bm + tags.
Oppgaven: Endret navn farger til engelsk + skrivefeil
=> Oppdatert kompetansemål web-partikkel-animasjon

src/web/hei_js/README.md, src/web/hei_js/lesson.yml
=> Oppdatert kompetansemål web-hei-js

src/web/style_nettsider/README.md, src/web/style_nettsider/lesson.yml, src/web/style_nettsider/style_nettsider.md, src/web/style_nettsider/style_nettsider_nn.md
Oppdatert LV bm + tags.
Oppgave: La til en parentese i introen for å forklare hvilke HTML-oppgaver det var snakk om.
=> Oppdatert kompetansemål web-style-nettsider

src/web/grunnleggende_js/README.md, src/web/grunnleggende_js/grunnleggende_js.md, src/web/grunnleggende_js/lesson.yml
Oppdatert LV bm + tags.
Oppgave bm: Rettet mange små skrivefeil
=> Oppdatert kompetansemål web-grunnleggende-js

src/web/forsvunnet_katt/README.md, src/web/forsvunnet_katt/lesson.yml
=> Oppdatert kompetansemål web-forsvunnet-katt

src/web/animasjon/README.md, src/web/forsvunnet_katt/README.md
=> Oppdatert kompetansemål web-animasjon

src/codestudio/Kurs1/README.md, src/codestudio/Kurs1/lesson.yml
=> Opprettet LV med kompetansemål kurs1

src/javafx/fxmllogo/README.md, src/javafx/fxmllogo/fxmllogo.md, src/javafx/fxmllogo/lesson.yml
=> Opprettet LV med kompetansemål javafx-fxmllogo

src/javafx/helloworld/README.md, src/javafx/helloworld/helloworld.md, src/javafx/helloworld/lesson.yml
=> Opprettet LV med kompetansemål javafx-helloworld

src/web/layout/README.md, src/web/layout/layout.md, src/web/layout/layout_nn.md, src/web/layout/lesson.yml
Oppdatert LV bm + tags + formatering
Oppgaven: skrivefeil + lagt til {target=_blank} på linker
=> Oppdatert kompetansemål web-layout

src/web/skjul_ninjaene/README.md, src/web/skjul_ninjaene/lesson.yml
Oppdatert LV bm + tags + formatering og skrivefeil
=> Oppdatert kompetansemål web-skjul-ninjaene

src/web/din_egen_nettside/README.md, src/web/din_egen_nettside/din_egen_nettside.md, src/web/din_egen_nettside/din_egen_nettside_nn.md, src/web/din_egen_nettside/lesson.yml
Oppdatert LV bm + tags + formatering.
Oppgaven: Lagt til tips om oppgaver fra oppgavesamling.
=> Oppdatert kompetansemål web-din-egen-nettside

src/web/hvor_er_html/README.md, src/web/hvor_er_html/README_nn.md, src/web/hvor_er_html/lesson.yml
Oppdatert LV bm, opprettet LV nn + oppdatert tags
=> Oppdatert kompetansemål web-hvor-er-html

src/web/en_hjemmeside/README.md, src/web/en_hjemmeside/README_nn.md, src/web/en_hjemmeside/lesson.yml
Oppdatert LV bm, opprettet LV nn + oppdatert tags
=> Oppdatert kompetansemål web-en-hjemmeside

src/codestudio/Kurs2/README.md, src/codestudio/Kurs2/lesson.yml
=> Opprettet LV med kompetansemål codestudio-kurs2

src/codestudio/Kurs3/README.md, src/codestudio/Kurs3/lesson.yml
=> Opprettet LV med kompetansemål codestudio-kurs3

src/codestudio/Kurs4/README.md, src/codestudio/Kurs4/lesson.yml
=> Opprettet LV med kompetansemål codestudio-kurs4

src/codestudio/AngryBirds/README.md, src/codestudio/AngryBirds/lesson.yml
=> Opprettet LV med kompetansemål codestudio-AngryBirds

src/codestudio/Frost/README.md, src/codestudio/Frost/frost.md, src/codestudio/Frost/lesson.yml
Oppgaven: lagt til intro spesifikk til oppgaven fra CS
=> Opprettet LV med kompetansemål codestudio-frost

src/codestudio/Minecraft/README.md, src/codestudio/Minecraft/lesson.yml
=> Opprettet LV med kompetansemål codestudio-minecraft

src/codestudio/StarWars/README.md, src/codestudio/StarWars/lesson.yml
=> Opprettet LV med kompetansemål codestudio-starwars

src/codestudio/Artist/README.md, src/codestudio/Artist/lesson.yml
=> Opprettet LV med kompetansemål codestudio-artist

src/codestudio/FlappyBird/README.md, src/codestudio/FlappyBird/lesson.yml
=> Opprettet LV med kompetansemål codestudio-flappybird

src/codestudio/Infinity/README.md, src/codestudio/Infinity/lesson.yml
=> Opprettet LV med kompetansemål codestudio-infinity

src/codestudio/ArtistApp/README.md, src/codestudio/ArtistApp/lesson.yml
=> Opprettet LV med kompetansemål codestudio-artistapp

src/codestudio/PlayLab/README.md, src/codestudio/PlayLab/lesson.yml
=> Opprettet LV med kompetansemål codestudio-playlab

src/codestudio/StarWarsJs/README.md, src/codestudio/StarWarsJs/lesson.yml
=> Opprettet LV med kompetansemål codestudio-starwarsjs

src/codestudio/AppLab/README.md, src/codestudio/AppLab/lesson.yml
Opprettet LV bm + oppdatert tags (endret til junior og senior siden CS anbefaler den for 13+)
=> Opprettet LV med kompetansemål codestudio-applab

src/arduino/blinkende_lysdiode/README.md, src/arduino/blinkende_lysdiode/blinkende_lysdiode.md, src/arduino/blinkende_lysdiode/lesson.yml
Oppdatert LV bm til riktig formatering + tags
Oppgaven: Skrivefeil
=> Oppdatert kompetansemål arduino-blinkende-lysiode

src/arduino/buzzer/README.md, src/arduino/buzzer/buzzer.md, src/arduino/buzzer/lesson.yml
Oppdatert LV bm med formatering + tags
Oppgaven: La til link til oppgaver referert til i introen.
=> Oppdatert kompetansemål arduino-buzzer

src/arduino/rgb_diode/README.md, src/arduino/rgb_diode/lesson.yml
Oppdatert LV bm med formatering + tags
=> Oppdatert kompetansemål arduino-RGB-diode

src/arduino/7_segment_display/README.md, src/arduino/7_segment_display/lesson.yml
Oppdatert LV bm med formatering + tags
=> Oppdatert kompetansemål arduino-7-segment-display

src/arduino/ultralydsensor/README.md, src/arduino/ultralydsensor/lesson.yml
Oppdatert LV bm med formatering + tags
=> Oppdatert kompetansemål arduino-ultralydsensor

src/processing/bildepresentasjon/README.md, src/processing/bildepresentasjon/lesson.yml
=> Oppdatert kompetansemål processing-bildepresentasjon

src/processing/farger/README.md
=> Oppdatert kompetansemål processing-farger

src/processing/interaktiv_intro/README.md, src/processing/interaktiv_intro/lesson.yml
Jeg valgte å ikke inkludere læringsmål og vurderingskriterier, siden oppgavesettet er såpass lang.
=> Opprettet LV med kompetansemål processing-interaktiv-intro

src/processing/sprettende_ball/README.md
=> Oppdatert kompetansemål processing-sprettende-ball

src/processing/tegnespillet/README.md, src/processing/tegnespillet/lesson.yml
=> Oppdatert kompetansemål processing-tegnespillet

src/processing/tetris/README.md, src/processing/tetris/lesson.yml
=> Oppdatert kompetansemål processing-tetris

src/processing/to_player/README.md, src/processing/to_player/lesson.yml
=> Oppdatert kompetansemål processing-to-player

src/processing/uendelig_bakke/README.md, src/processing/uendelig_bakke/lesson.yml
=> Oppdatert kompetansemål processing-uendelig-bakke

src/processing/mangekanter/README.md
=> Oppdatert kompetansemål processing-mangekanter

src/processing/verden_del1/README.md
=> Oppdatert kompetansemål processing-verden-del1

src/processing/pingpong/README.md, src/processing/pingpong/lesson.yml
=> Oppdatert kompetansemål processing-pingpong

src/processing/trigonometri/README.md
=> Oppdatert kompetansemål processing-trigonometri

src/processing/verden_del2/README.md
=> Oppdatert kompetansemål processing-verden-del2

src/learntomod/bygge_en_kube/README.md, src/learntomod/bygge_en_kube/lesson.yml
=> Opprettet LV med kompetansemål learntomd-bygge-en-kube

src/learntomod/bygge_en_pyramide/README.md, src/learntomod/bygge_en_pyramide/bygge_en_pyramide.md, src/learntomod/bygge_en_pyramide/lesson.yml
Oppgave: La til link til oppgave referert.
=> Opprettet LV med kompetansemål learntomod-bygge-en-pyramide

src/learntomod/bygge_et_hus/README.md, src/learntomod/bygge_et_hus/lesson.yml
=> Opprettet LV med kompetansemål learntomod-bygge-et-hus

src/computercraft/introduksjon_til_computercraft/README.md, src/computercraft/introduksjon_til_computercraft/lesson.yml
=> Opprettet LV med kompetansemål computercraft-introduksjon-til-cc

src/computercraft/bli_kjent_med_datamaskinen/README.md, src/computercraft/bli_kjent_med_datamaskinen/lesson.yml
=> Opprettet LV med kompetansemål computercraft-bli-kjent

src/computercraft/robotinvasjon/README.md, src/computercraft/robotinvasjon/lesson.yml
=> Opprettet LV med kompetansemål computercraft-robotinvasjon

src/computercraft/bygg_et_hus/README.md, src/computercraft/bygg_et_hus/bygg_et_hus.md, src/computercraft/bygg_et_hus/lesson.yml
Oppgaven: Fikset stor forbokstav i tittel
=> Opprettet LV med kompetansemål computercraft-bygg-et-hus

src/computercraft/hendelser/README.md, src/computercraft/hendelser/hendelser.md, src/computercraft/hendelser/lesson.yml
Oppgave: Lagt til link computercraft-hendelser
=> Opprettet LV med kompetansemål computercraft-hendelser

src/computercraft/nettverk_send_beskjed/README.md, src/computercraft/nettverk_send_beskjed/lesson.yml
=> Opprettet LV med kompetansemål computercraft-nettverk-send-beskjed

src/computercraft/fjernstyr_en_robot/README.md, src/computercraft/fjernstyr_en_robot/fjernstyr_en_robot.md, src/computercraft/fjernstyr_en_robot/lesson.yml
=> Opprettet LV med kompetansemål computercraft-fjernstyr-en-robot

src/computercraft/sprettball/README.md, src/computercraft/sprettball/lesson.yml
=> Opprettet LV med kompetansemål computercraft-sprettball

src/microbit/pxt_microbit_repeater/README.md, src/microbit/pxt_microbit_repeater/lesson.yml
Opprettet Lv bm + oppdatert tags
(Jeg hadde visst ikke fått lagt til denne PR...)
=> Opprettet Lv med komptansemål m:b-PXT-microbit-repeater

src/scratch/flaksefugl/flaksefugl.md, src/scratch/flaksefugl/flaksefugl_nn.md
Flaksefugl has a challenge for making top score function using network variables which are no longer available in scratch.
=> Network variables are not available any more

src/microbit/pxt_terning/terning.md
Blokken show leds heter vis skjerm på norsk
=> Norsk navn på blokk

src/microbit/pxt_lagegetbilde/egetbilde.md
Show leds heter vis skjerm på norsk - som vist på bildet av blokken
=> Norsk tekst på blokk

src/microbit/pxt_er_du_rask_nok/rask_nok.md, src/microbit/pxt_stein_saks_papir/stein_saks_papir.md, src/microbit/pxt_temperatur/temperatur.md, src/microbit/pxt_temperatur/temperatur_nn.md, src/microbit/pxt_trykkforbilde/trykkforbilde.md
Gjort navneendring fra 'show leds' til 'vis skjerm' på alle micro:bit-oppgavene.
=> Endre navn fra show leds til vis skjerm

.github/workflows/dependabot.yml
Den vil automatisk lage pr. når noen github action er utdatert
=> la til dependabot for github action

src/microbit/kodetimen-magnetfeltovelse/kodetimen-magnetfeltovelse.md
Slettet bilde av død kloss med "inklinasjon".
=> Slettet "død kloss" bildet

src/scratch/soloball/soloball.md
Variablen 'retning av katt' heter 'kattens retning' på ett sted i koden.
=> Korrigering av variable navn i soloball.md
